NEXT = 'next'
ORDER_BY = 'order_by'
SORT = 'sort'
LIMIT = 'limit'
CURSOR = 'cursor'
ORDERING = 'ordering'

NAME = 'name'
ID = 'id'
CATEGORY = 'category'
PART = 'part'
LOCATION = 'location'
SUPPLIER = 'supplier'
TIMESTAMP_GTE = 'timestamp_gte'
TIMESTAMP_LTE = 'timestamp_lte'
PK = 'pk'

ASC = 'ASC'
DESC = 'DESC'

NULL = 'null'
OBJECTS = 'objects'

CHECK_SERIALIZER = 'check_serializer'
OUTPUT_CHECK_SERIALIZER = 'output_check_serializer'

#Tables
TABLE_ACCOUNT = 'account'
TABLE_AUTH_GROUP = 'auth_group'
TABLE_COMPANY = 'company'
TABLE_ACCOUNT_FILE = 'account_files'
TABLE_ASSET_CATEGORY = 'asset_category'
TABLE_ASSET = 'asset'
TABLE_LOCATION = 'location'
TABLE_ACCOUNT_ASSET = 'account_asset'
TABLE_ASSET_FILES = 'asset_files'
TABLE_MAINTENANCE_TYPE = 'maintenance_type'
TABLE_MAINTENANCE_CATEGORY = 'maintenance_category'
TABLE_PART_CATEGORY = 'part_category'
TABLE_SUPPLIER_CATEGORY = 'supplier_category'
TABLE_SUPPLIER = 'supplier'
TABLE_COMPANY_SETTINGS = 'company_settings'
TABLE_PARTNER_COMPANY_REQUEST = 'partner_company_request'
TABLE_PARTNER_COMPANY = 'partner_company'

#Procedures
PROC_ACCOUNT_ADD = 'account_add'
PROC_ASSET_ADD = 'asset_add'
PROC_ASSET_CHANGE_PARENT = 'asset_change_parent'