# Generated by Django 3.2.11 on 2024-08-14 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240814_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reg_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='reg_token_is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
