# Generated by Django 3.2.11 on 2024-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240814_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtokenemail',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
